<!DOCTYPE html><html lang="en">
<head>
    <title>Zend Framework Util Library</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/calendar.css'); ?>" type="text/css" media="screen">
</head>
<body>

    <?php echo $this->layout()->content; ?>

</body>
</html>